# Generated by Django 5.1.1 on 2024-09-20 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='completed',
            new_name='Completed',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='title',
        ),
        migrations.AddField(
            model_name='todo',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 20, 18, 11, 7, 149585, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='todo',
            name='Description',
            field=models.TextField(blank=True, default='Lorem Ipsum'),
        ),
        migrations.AddField(
            model_name='todo',
            name='Title',
            field=models.CharField(default='John Doe', max_length=100),
        ),
    ]
